# Generated by Django 5.1.6 on 2025-03-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='TEMPORDER123', editable=False, max_length=12, unique=True),
        ),
    ]
