# Generated by Django 5.1.6 on 2025-03-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line_1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line_2',
            new_name='address_line2',
        ),
    ]
