# Generated by Django 5.1.6 on 2025-03-23 12:59

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='GB', max_length=2),
            preserve_default=False,
        ),
    ]
