# Generated by Django 5.1.6 on 2025-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
