# Generated by Django 5.1.6 on 2025-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(choices=[('piece', 'Per Piece'), ('gram', 'Per Gram'), ('kilogram', 'Per Kilogram')], default='piece', max_length=10),
        ),
    ]
